### ISSUE TITLE
MacOS Compatability

### ISSUE THREAD

**Issue by zachmcd09** [VideotronicMaker/LM-Studio-Voice-Conversation#1]
Does not work on M1 Macbook Air, working on compatible version.

**Comment by VideotronicMaker** [comment]
If you have LM Studio running and the script is running but the voice is not working, try deleting this block of code from the "speak.py" file.  These are lines 15-20 in the original script.  I had to add this to force Windows to use my selected voice.  However, I initially used the Windows voice pkg without that code but windows played the wrong voice.  Since Mac OS does not apply here, maybe this will help.  I am unsure of what trouble you encountered but that was something obvious for Mac users that I did not point out earlier.  Mac users do not need this block as it is specific to Windows.

Code block to delete:


# Initialize Text-to-Speech engine with Hazel's voice
engine = pyttsx3.init()
hazel_voice_id = "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-GB_HAZEL_11.0"
engine.setProperty('voice', hazel_voice_id)
engine.say("Hello Videotronic Maker, How can I assist you today sir?")
engine.runAndWait()

Hope this helps.
